package com.time.yourguideapp.presentation.explore

internal data class ExploreVideo(
    val id: String,
    val youtubeId: String,
    val title: String,
    val location: String,
    val description: String,
    val likes: String,
    val comments: String,
)

internal val dummyExploreVideos = listOf(
    ExploreVideo(
        id = "bali-beach",
        youtubeId = "QFxN2oDKk0E",
        title = "Bali Beach Walk",
        location = "Canggu, Bali",
        description = "Sunset route, beach clubs, and a quiet corner near the shore.",
        likes = "12.4K",
        comments = "348",
    ),
    ExploreVideo(
        id = "bali-beach",
        youtubeId = "QFxN2oDKk0E",
        title = "Bali Beach Walk",
        location = "Canggu, Bali",
        description = "Sunset route, beach clubs, and a quiet corner near the shore.",
        likes = "12.4K",
        comments = "348",
    ),
    ExploreVideo(
        id = "bali-beach",
        youtubeId = "QFxN2oDKk0E",
        title = "Bali Beach Walk",
        location = "Canggu, Bali",
        description = "Sunset route, beach clubs, and a quiet corner near the shore.",
        likes = "12.4K",
        comments = "348",
    ),
    ExploreVideo(
        id = "bali-beach",
        youtubeId = "QFxN2oDKk0E",
        title = "Bali Beach Walk",
        location = "Canggu, Bali",
        description = "Sunset route, beach clubs, and a quiet corner near the shore.",
        likes = "12.4K",
        comments = "348",
    ),
    ExploreVideo(
        id = "bali-beach",
        youtubeId = "QFxN2oDKk0E",
        title = "Bali Beach Walk",
        location = "Canggu, Bali",
        description = "Sunset route, beach clubs, and a quiet corner near the shore.",
        likes = "12.4K",
        comments = "348",
    ),
    ExploreVideo(
        id = "bali-beach",
        youtubeId = "QFxN2oDKk0E",
        title = "Bali Beach Walk",
        location = "Canggu, Bali",
        description = "Sunset route, beach clubs, and a quiet corner near the shore.",
        likes = "12.4K",
        comments = "348",
    ),
    ExploreVideo(
        id = "bali-beach",
        youtubeId = "QFxN2oDKk0E",
        title = "Bali Beach Walk",
        location = "Canggu, Bali",
        description = "Sunset route, beach clubs, and a quiet corner near the shore.",
        likes = "12.4K",
        comments = "348",
    ),   ExploreVideo(
        id = "bali-beach",
        youtubeId = "QFxN2oDKk0E",
        title = "Bali Beach Walk",
        location = "Canggu, Bali",
        description = "Sunset route, beach clubs, and a quiet corner near the shore.",
        likes = "12.4K",
        comments = "348",
    ),   ExploreVideo(
        id = "bali-beach",
        youtubeId = "QFxN2oDKk0E",
        title = "Bali Beach Walk",
        location = "Canggu, Bali",
        description = "Sunset route, beach clubs, and a quiet corner near the shore.",
        likes = "12.4K",
        comments = "348",
    ),
    ExploreVideo(
        id = "bali-beach",
        youtubeId = "QFxN2oDKk0E",
        title = "Bali Beach Walk",
        location = "Canggu, Bali",
        description = "Sunset route, beach clubs, and a quiet corner near the shore.",
        likes = "12.4K",
        comments = "348",
    ),
    ExploreVideo(
        id = "bali-beach",
        youtubeId = "QFxN2oDKk0E",
        title = "Bali Beach Walk",
        location = "Canggu, Bali",
        description = "Sunset route, beach clubs, and a quiet corner near the shore.",
        likes = "12.4K",
        comments = "348",
    ),
    ExploreVideo(
        id = "bali-beach",
        youtubeId = "QFxN2oDKk0E",
        title = "Bali Beach Walk",
        location = "Canggu, Bali",
        description = "Sunset route, beach clubs, and a quiet corner near the shore.",
        likes = "12.4K",
        comments = "348",
    ),
    ExploreVideo(
        id = "bali-beach",
        youtubeId = "QFxN2oDKk0E",
        title = "Bali Beach Walk",
        location = "Canggu, Bali",
        description = "Sunset route, beach clubs, and a quiet corner near the shore.",
        likes = "12.4K",
        comments = "348",
    ),


    ExploreVideo(
        id = "bali-beach",
        youtubeId = "QFxN2oDKk0E",
        title = "Bali Beach Walk",
        location = "Canggu, Bali",
        description = "Sunset route, beach clubs, and a quiet corner near the shore.",
        likes = "12.4K",
        comments = "348",
    ),
    ExploreVideo(
        id = "kyoto-street",
        youtubeId = "hZ1Rb9hC4JY",
        title = "Kyoto Street Notes",
        location = "Kyoto, Japan",
        description = "Narrow alleys, warm lights, and small stops for your next itinerary.",
        likes = "8.9K",
        comments = "192",
    ),
    ExploreVideo(
        id = "swiss-view",
        youtubeId = "linlz7-Pnvw",
        title = "Swiss Viewpoint",
        location = "Lauterbrunnen, Switzerland",
        description = "A quick look at the valley before the morning crowd arrives.",
        likes = "21K",
        comments = "571",
    ),
    ExploreVideo(
        id = "city-food",
        youtubeId = "M7lc1UVf-VE",
        title = "City Food Stop",
        location = "Night Market",
        description = "Fast bites worth saving before you move to the next district.",
        likes = "6.1K",
        comments = "84",
    ),
    ExploreVideo(
        id = "desert-road",
        youtubeId = "ScMzIvxBSi4",
        title = "Desert Road",
        location = "Open Route",
        description = "Long road energy with a few stops that make the drive worth it.",
        likes = "15.7K",
        comments = "421",
    ),
)
